// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQY8il78zs23Hc8f0TpRbxf2kvK5toyI',
    appId: '1:780662687779:web:8d0406e730911b9992c996',
    messagingSenderId: '780662687779',
    projectId: 'testform-c3f60',
    authDomain: 'testform-c3f60.firebaseapp.com',
    storageBucket: 'testform-c3f60.appspot.com',
    measurementId: 'G-72PC453VBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtsKLkbBkD1jf0WMAVvvXVE06HbZRDFxs',
    appId: '1:780662687779:android:7a6f8eecd418c3a392c996',
    messagingSenderId: '780662687779',
    projectId: 'testform-c3f60',
    storageBucket: 'testform-c3f60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQ5tDZP2QLXEYBnmqgmh_2A1ttnDer8E',
    appId: '1:780662687779:ios:19b46deba6077d8b92c996',
    messagingSenderId: '780662687779',
    projectId: 'testform-c3f60',
    storageBucket: 'testform-c3f60.appspot.com',
    iosClientId: '780662687779-biul3jq2bbvcttm20f6hc94pj9k3r5d5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testform',
  );
}
